services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: budgetify-client-1
    ports:
      - 5173:5173

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: budgetify-server-1
    ports:
      - 8000:8000

  db:
    image: mongo
    ports:
      - 27017:27017
